# Generated by Django 3.1.2 on 2020-10-01 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('added_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=3000)),
                ('added_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('added_at', models.DateTimeField(verbose_name='date published')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='inventory.comments')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='inventory.recipe'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('info', models.TextField(max_length=3000)),
                ('pic', models.ImageField(upload_to='images')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='inventory.comments')),
                ('recipes', models.ManyToManyField(db_index=True, related_name='author', to='inventory.Recipe')),
            ],
        ),
    ]
