# Generated by Django 3.1.2 on 2020-10-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201012_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(to='inventory.Tag', verbose_name='Tags'),
        ),
    ]
