# Generated by Django 3.1.2 on 2020-10-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20201003_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
