# Generated by Django 3.1.2 on 2020-10-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=400, unique=True),
        ),
    ]
